#!/bin/bash

# This script would delete all the files from a specific path
# The goal is to use this script with crontab to run it periodically
# and avoid filling up the disk
# This script will be used to delete log files generated by VCC

# Version Specific Comments#
# find will return all the logs files that were modified 2 minutes or more ago
# so the file is not currently being used

for f in $(find /home/testUser/test/* -type f -mmin +2)
  do
    logger "Trying to delete: $f"
    rm $f
    if [ $? -eq 0 ]; then
      logger "SUCCESS deleting file $f"
    else
      logger "ERROR deleting file $f"
    fi
  done
